spring:
  application:
    name: ranking
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
    streams:
      application-id: profit-ranking-app-v3
      state-dir: /tmp/kafka-streams
      replication-factor: 1
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        num.stream.threads: 1
        processing.guarantee: exactly_once_v2

topics:
  execution: finance.finance.execution
  out: notify.ranking.top10
